# !-----------------------------------------------------------------------------------------------!
#                       Добро пожаловать в главный файл конфигурации плагина ${project.name}
# !-----------------------------------------------------------------------------------------------!
#
#   1) ЦВЕТОВЫЕ КОДЫ поддерживаются символом '&'.
#      - Для примера смотрите http://minecraftwiki.net/wiki/Formatting_codes
#      - Когда используете цветовые коды, оборачивайте текст кавычками: "Hello &cworld."
#      - Чтобы использовать HEX цвета, используйте следующий синтаксис: #123456 - "Hello #123456world."
#
#   2) ЧТОБЫ СКРЫТЬ любое сообщение, поставьте его значение на 'none'.
#
#   3) Для использования СИМВОЛОВ ЮНИКОДА (смайликов, символов и т.д.), сохраните файл в кодировке UTF-8.
#
#   4) Поддерживается JSON. Добавьте в начало сообщения [JSON].
#
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# Какой язык нам использовать для сообщений? Если перевод на этот язык есть в плагине,
# он будет автоматически скопирован в папку messages, где Вы сможете редактировать все сообщения
# -------------------------------------------------------------------------------------------------
Locale: ru

# -------------------------------------------------------------------------------------------------
# Префикс, используемый перед сообщениями в чате и консоли.
# Вы можете использовать префикс где захотите, введя {plugin_prefix}.
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&c${project.name}&8]&7 "

# -------------------------------------------------------------------------------------------------
# Для администраторов: не меняйте это значение, иначе настройки плагина слетят!
# Для разработчиков: постоянно обновляйте это значение в соответствии с getConfigVersion в классе Settings.
# -------------------------------------------------------------------------------------------------
Version: 1